name: Checking the codebase

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
    
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements.dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./app_python/requirements.txt ]; then pip install -r ./app_python/requirements.txt; fi
        if [ -f ./app_python/requirements.dev.txt ]; then pip install -r ./app_python/requirements.dev.txt; fi

    - name: Linter
      run: |
        cd app_python
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Tests
      run: |
        cd app_python
        python -m pytest tests/
  
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Scan for vulnerabilities with Snyk
      uses: snyk/actions/setup-snyk@master
      with:
        snyk_token: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --all-projects

