name: Checking the codebase

on:
  push:
    paths:
      - '**' #'app_python/**'

defaults:
  run:
    working-directory: app_python

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
        cache: 'pip'

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: Linter
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Tests
      run: python -m pytest tests/
  
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2
          cache: 'pip'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Install snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: snyk test --sarif-file-output=./snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: kek
        run: ls

      - name: kek
        run: cd ..

      - name: kek
        run: ls
      
      - name: kek
        run: cd app_python
      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./snyk.sarif

